### ISSUE TITLE
Как использовать мобильный телефон пользователя?

### ISSUE THREAD

**Issue by vslinko** [ivan2020/alexis#5]
@rithis/alexis-staff

**Comment by ivan2020** [comment]
Номер телефона чел сам не вводит. Он записывается автоматом при подтверждении своей реальности через смс. Этим он повышает свой статус и возможности заведения знакомств. Другие пользователи могут у себя в профиле поставить галку, что хотят общаться только с реальными пользователями и соответственно их профили будут показываться только тем, кто подтвердил свою реальность, отправив смс.

**Comment by ranzhe** [comment]
> Номер телефона чел сам не вводит. Он записывается автоматом при подтверждении своей реальности через смс. 

Мб я чего не понял, а при подтверждении он откуда возьмется, если не путем ввода, собственно, челом?

**Comment by vslinko** [comment]
Он отправляет

travel 534576 на номер 4242

Мы можем зацепить номер.

---

Sincerely yours
Vyacheslav Slinko
